services:
  db:
    image: pgvector/pgvector:pg16
    container_name: tech_news_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tech_news
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: tech_news_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
