services:
  app:
    build: .
    container_name: tech_news_api
    restart: always
    expose:
      - "3000"
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/tech_news?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Caso use URL completa para Redis tamb√©m:
      # REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis

  db:
    image: pgvector/pgvector:pg16
    container_name: tech_news_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tech_news
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: tech_news_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
